### ISSUE TITLE
Error 'PromptExecutor' object has no attribute 'outputs'

### ISSUE THREAD

**Issue by T-star-x** [nkchocoai/ComfyUI-SaveImageWithMetaData#34] opened 2024-08-16 09:44 UTC
Hello

First, thank you for the work of everyone involved!

I am a little afraid this issue may not realy actually be caused by ComfyUI-SaveImageWithMetaData. I am totaly new to ConfyUI and AI Image generation and just started setting ConfyUI up with a Flux model. In order to store the promt into my images I downloaded this Node and included it into my first workflow. As soon as the image is to be stored I get the error I post below. I tried to find anything comparable on the net, but had no success. So I turn to the place where this acutally occures. I did append the Workflow and I will be very gratefull for any advice how to resolve this issue:

Error occurred when executing SaveImageWithMetaData:

'PromptExecutor' object has no attribute 'outputs'

  File "X:\Base\ComfyUI_windows_portable\ComfyUI\execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Base\ComfyUI_windows_portable\ComfyUI\execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Base\ComfyUI_windows_portable\ComfyUI\execution.py", line 165, in map_node_over_list
    process_inputs(input_dict, i)
  File "X:\Base\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Base\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 79, in save_images
    pnginfo_dict_src = self.gen_pnginfo(
                       ^^^^^^^^^^^^^^^^^
  File "X:\Base\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 165, in gen_pnginfo
    inputs = Capture.get_inputs()
             ^^^^^^^^^^^^^^^^^^^^
  File "X:\Base\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\capture.py", line 18, in get_inputs
    outputs = hook.prompt_executer.outputs
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[Error_Workflow Flux-dev.json](https://github.com/user-attachments/files/16635667/Error_Workflow.Flux-dev.json)

Thank you and keep up the good work!

**Comment by Vik71it** [comment] 2024-08-16 22:01
This happens also to me, with two ComfyUI rel, b021cf6 (one of the freshly installed) but not with a rel. 0f9c2a7, for the moment

**Comment by simon-kyger** [comment] 2024-08-16 23:25
yeah updating comfyui broke this again :(

**Comment by nkchocoai** [comment] 2024-08-17 03:54
The issue is reproduced in my environment.
Please wait a moment as there has been a change in the core logic.

**Comment by simon-kyger** [comment] 2024-08-17 06:00
in the meanwhile, for those of you still using this save image w/ metadata you can roll comfyui back a patch, this was the previous comfyui, just dont update comfyui until this node has been fixed.  change cd directory path to your comfyui install path.

`cd C:\ComfyUI_windows_portable\ComfyUI
git checkout 0f9c2a78224ce3179c773fe3af63722f438b0613 .`

**Comment by Annamae-beep** [comment] 2024-08-17 12:40
I knew I should have installed with git (no such repository). I will have to wait for node fix I guess.

**Comment by Annamae-beep** [comment] 2024-08-20 06:25
Thank you so much, it works for me now.

**Comment by ardri1166** [comment] 2024-08-20 15:46
> Thank you so much, it works for me now.

wdym works for you? I'm still getting the same error after updating.

**Comment by ninjaeon** [comment] 2024-08-20 15:57
> > Thank you so much, it works for me now.
> 
> wdym works for you? I'm still getting the same error after updating.

The pull request hasn't been merged yet.  I tested it and it also fixed this issue for me.

I'm not sure if this is the "proper" method of doing this, but this is how I updated this node to include the changes in the pull request:

Goto the ...\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData directory and ran the following commands:

git fetch origin pull/35/head:pr-35-branch
git checkout pr-35-branch

**Comment by ninjaeon** [comment] 2024-08-20 16:24
Another option to get the fix without waiting for the official branch to be updated is to download the fork with the fix included:  https://github.com/TheBill2001/ComfyUI-SaveImageWithMetaData

**Comment by Annamae-beep** [comment] 2024-08-20 18:06
> > Thank you so much, it works for me now.
> 
> wdym works for you? I'm still getting the same error after updating.

I cloned the fork: https://github.com/TheBill2001/ComfyUI-SaveImageWithMetaData

**Closed** 2024-08-21 15:45 UTC

**Comment by nkchocoai** [comment] 2024-08-21 15:53
Thanks for the report and workaround.
I have merged #35 .
